# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        
      - name: Install deps
        run: npm install
      
      - name: Build typescript
        run: npx tsc -p tsconfig.json
        
      - name: Archive build artifact
        uses: actions/upload-artifact@v2
        with:
          name: cowbot-build
          path: dist
          
  build-image:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    - name: Detect and Tag New Version
      uses: salsify/action-detect-and-tag-new-version@v2.0.1
      
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: cowbot-build
        path: dist/
      
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=snaekomu/cowbot
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=nightly
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        platforms: linux/arm/v7
        push: true
        tags: ${{ steps.prep.outputs.tags }}

